# Generated by Django 5.0.6 on 2024-06-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickfoods', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
